repos:
  - repo: local
    hooks:
      - id: format
        language: system
        name: cargo fmt
        entry: cargo fmt
        pass_filenames: false
        stages:
          - commit
      - id: check
        language: system
        name: cargo check
        entry: cargo check
        pass_filenames: false
        stages:
          - commit
