repos:
  - repo: local
    hooks:
      - id: format
        language: system
        name: cargo fmt
        entry: cargo fmt
        pass_filenames: false
        stages:
          - pre-commit
      - id: check
        language: system
        name: cargo check
        entry: cargo check
        pass_filenames: false
        stages:
          - pre-commit
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      # Run the linter.
      - id: ruff
        args: ["pythondap"]
      # Run the formatter.
      - id: ruff-format
        args: ["pythondap"]

