repos:
  - repo: local
    hooks:
      - id: format
        language: system
        name: cargo fmt
        entry: cargo fmt --check
        pass_filenames: false
        stages:
          - commit
