repos:
  - repo: local
    hooks:
      - id: format
        language: system
        name: cargo fmt
        entry: cargo fmt
        pass_filenames: false
        stages:
          - pre-commit
      - id: check
        language: system
        name: cargo check
        entry: cargo check
        pass_filenames: false
        stages:
          - pre-commit
      - id: test
        language: system
        name: cargo test
        entry: bash -c "source ./.venv/bin/activate && cargo nextest run"
        pass_filenames: false
        stages:
          - pre-push
