repos:
  - repo: https://github.com/backplane/pre-commit-rust-hooks
    rev: v1.1.0
    hooks:
    - id: fmt
    - id: check
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      # Run the linter.
      - id: ruff
        args: ["pythondap"]
      # Run the formatter.
      - id: ruff-format
        args: ["pythondap"]
  # pre-push configuration
  - repo: https://github.com/backplane/pre-commit-rust-hooks
    rev: v1.1.0
    hooks:
    - id: clippy
    - id: test
    stages:
      - pre-push

