repos:
  - repo: local
    hooks:
      - id: cargo test
        language: system
        name: cargo test
        entry: cargo test --no-run
        pass_filenames: false
        stages:
          - commit
          - push
