[workspace]
release = true
publish = false
semver_check = false
changelog_update = false
git_only = true
git_release_enable = false

[[package]]
name = "dap-tui"
changelog_update = true
git_tag_name = "v{{ version }}"
git_release_name = "v{{ version }}"
git_release_enable = true

[[package]]
name = "xtask"
release = false
