[workspace]
release = false
semver_check = false
publish = false
changelog_update = false

[[package]]
name = "dap-tui"
release = true
git_only = true
changelog_update = true
git_tag_name = "v{{ version }}"
git_release_name = "v{{ version }}"
git_release_enable = true
release_commits = "all"
