[package]
name = "transport"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
spmc.workspace = true
tracing.workspace = true
bytes = "1.4.0"
oneshot = { version = "0.1.5", default-features = false, features = ["std"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"

[dev-dependencies]
tracing-subscriber = { version = "0.3.18", features = ["json", "env-filter"] }
