[package]
name = "transport"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre.workspace = true
crossbeam-channel.workspace = true
tracing.workspace = true
bytes = "1.4.0"
oneshot = { version = "0.1.5", default-features = false, features = ["std"] }
serde_json = "1.0.111"
serde.workspace = true
nom = { version = "7.1.3", optional = true }

[dev-dependencies]
color-eyre.workspace = true
tracing-subscriber = { version = "0.3.18", features = ["json", "env-filter"] }
server = { path = "../server" }
criterion = "0.5.1"
ctor.workspace = true

[[bench]]
name = "parser"
harness = false

[features]
nom = ["dep:nom"]
