[package]
name = "dap-debugger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dap-gui-client = { path = "../dap-gui-client" }
tracing = "0.1.37"
anyhow = "1.0.71"
