[package]
name = "pcaplog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
clap = { version = "4.4.11", features = ["derive"] }
etherparse = "0.13.0"
pcap-parser = "0.14.1"
tracing.workspace = true
tracing-subscriber = "0.3.18"
