[package]
name = "dap-codec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.37.0", features = ["net"] }
tokio-util = { version = "0.7.10", features = ["codec"] }
dap = { git = "https://github.com/simonrw/dap-rs", rev = "5bdc158225c995219ca71a2887d871a156a117d9" }
bytes = "1.6.0"
thiserror = "1.0.58"
